database:
  name: dm_item
server:
  port: 7201
spring:
  application:
    name: dm-item
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8
        # jdbc:mysql://localhost:3306/dm_item?useUnicode=true&characterEncodeing=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka, http://localhost:8762/eureka
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.hdax.dm.entity.item